### PR TITLE
Support Tools

### PR DESCRIPTION
**Pull request by iwamot**
Experimental.

Currently does not work with Bedrock.
https://github.com/BerriAI/litellm/issues/2615

### CODE REVIEW

**Comment by ghost** [comment]
is this still true? @iwamot 

the converse pr merge should have fixed this

**Comment by iwamot** [comment]
@krrishdholakia Thank you for letting me know. I will take some time later to check it out.

**Comment by ghost** [comment]
relevant pr - https://github.com/BerriAI/litellm/pull/4106

**Comment by iwamot** [comment]
@krrishdholakia
As reported at https://github.com/BerriAI/litellm/issues/4091#issuecomment-2191126832, `stream_chunk_builder` omits `tool_calls` information.
At this time, I intend to change the logic so that `stream_chunk_builder` is not used.

**Comment by ghost** [comment]
how do you use `stream_chunk_builder` @iwamot 

will help to understand e2e flow

**Comment by iwamot** [comment]
@krrishdholakia
Thank you for your consideration.

In app/litellm_ops.py, `delta.tool_calls` processing is complicated, so I wanted to save each stream response in chunks and merge them later.

```python
    chunks: List = []
    try:
        loading_character = " ... :writing_hand:"
        for chunk in stream:
            spent_seconds = time.time() - start_time
            if timeout_seconds < spent_seconds:
                raise TimeoutError()
            chunks.append(chunk)  # Save each stream response
            item = chunk.choices[0]
            if item.get("finish_reason") is not None:
                break
            delta = item.get("delta")
            if delta.get("content") is not None:
                word_count += 1
                assistant_reply["content"] += delta.get("content")
                if word_count >= 20:

                    def update_message():
                        assistant_reply_text = format_assistant_reply(
                            assistant_reply["content"], translate_markdown
                        )
                        wip_reply["message"]["text"] = assistant_reply_text
                        update_wip_message(
                            client=client,
                            channel=context.channel_id,
                            ts=wip_reply["message"]["ts"],
                            text=assistant_reply_text + loading_character,
                            messages=messages,
                            user=user_id,
                        )

                    thread = threading.Thread(target=update_message)
                    thread.daemon = True
                    thread.start()
                    threads.append(thread)
                    word_count = 0

        for t in threads:
            try:
                if t.is_alive():
                    t.join()
            except Exception:
                pass

        response = litellm.stream_chunk_builder(chunks)  # Merge them
        if hasattr(response.choices[0].message, "tool_calls"):
```

Proper handling of `delta.tool_calls` would solve this, but if `stream_chunk_builder` handles it wisely, that would be more helpful.

**Comment by ghost** [comment]
> Proper handling of delta.tool_calls would solve this

oh is there something we're doing wrong here? @iwamot

**Comment by iwamot** [comment]
@krrishdholakia 

Each streaming response seems OK:
```
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='Certainly', role='assistant', function_call=None, tool_calls=None), logprobs=None)], created=1719390703, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='!', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' I', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content="'", role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='d be', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' happy', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' to', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' check', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' the', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' current', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' weather', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' in', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' Boston', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' for', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' you', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='.', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' I', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content="'ll", role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' use', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' the', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' get', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='_', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='current', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='_', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='weather', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' function', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' to', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' retrieve', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' this', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' information', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='.', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' Let', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' me', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390704, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' ', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390705, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='do that', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390705, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' for', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390705, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' you', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390705, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' right', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390705, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=' away', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390705, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='.', role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390705, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='', role=None, function_call=None, tool_calls=[ChatCompletionDeltaToolCall(id='tooluse_zTxxCmxmSGin4tOxR39g3w', function=Function(arguments='', name='get_current_weather'), type='function', index=0)]), logprobs=None)], created=1719390706, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='', role=None, function_call=None, tool_calls=[ChatCompletionDeltaToolCall(id=None, function=Function(arguments='', name=None), type='function', index=0)]), logprobs=None)], created=1719390706, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='', role=None, function_call=None, tool_calls=[ChatCompletionDeltaToolCall(id=None, function=Function(arguments='{"location', name=None), type='function', index=0)]), logprobs=None)], created=1719390706, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='', role=None, function_call=None, tool_calls=[ChatCompletionDeltaToolCall(id=None, function=Function(arguments='": "Boston', name=None), type='function', index=0)]), logprobs=None)], created=1719390706, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='', role=None, function_call=None, tool_calls=[ChatCompletionDeltaToolCall(id=None, function=Function(arguments=', ', name=None), type='function', index=0)]), logprobs=None)], created=1719390706, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='', role=None, function_call=None, tool_calls=[ChatCompletionDeltaToolCall(id=None, function=Function(arguments='MA"', name=None), type='function', index=0)]), logprobs=None)], created=1719390706, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='', role=None, function_call=None, tool_calls=[ChatCompletionDeltaToolCall(id=None, function=Function(arguments=', "unit":', name=None), type='function', index=0)]), logprobs=None)], created=1719390706, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='', role=None, function_call=None, tool_calls=[ChatCompletionDeltaToolCall(id=None, function=Function(arguments=' "', name=None), type='function', index=0)]), logprobs=None)], created=1719390706, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='', role=None, function_call=None, tool_calls=[ChatCompletionDeltaToolCall(id=None, function=Function(arguments='fahren', name=None), type='function', index=0)]), logprobs=None)], created=1719390706, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='', role=None, function_call=None, tool_calls=[ChatCompletionDeltaToolCall(id=None, function=Function(arguments='heit"}', name=None), type='function', index=0)]), logprobs=None)], created=1719390706, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[StreamingChoices(finish_reason='tool_calls', index=0, delta=Delta(content=None, role=None, function_call=None, tool_calls=None), logprobs=None)], created=1719390706, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion.chunk', system_fingerprint=None)
```

`stream_chunk_builder` omits `tool_calls` information:
```
ModelResponse(id='chatcmpl-33110b19-c247-4f0c-9078-1b1834fa78ac', choices=[Choices(finish_reason='tool_calls', index=0, message=Message(content="Certainly! I'd be happy to check the current weather in Boston for you. I'll use the get_current_weather function to retrieve this information. Let me do that for you right away.", role='assistant'))], created=1719390703, model='anthropic.claude-3-5-sonnet-20240620-v1:0', object='chat.completion', system_fingerprint=None, usage=Usage(completion_tokens=38, prompt_tokens=0, total_tokens=38))
```

Therefore, I believe that if that merging process is improved, the problem will be solved.

**Pull request merged**
